"""Add encrypted provider connections, model discovery, and versioned pricing."""
from datetime import datetime,timezone
from alembic import op
import sqlalchemy as sa
revision="0007";down_revision="0006";branch_labels=None;depends_on=None
SOURCE="https://developers.openai.com/api/docs/models/compare"
def upgrade():
    bind=op.get_bind();inspector=sa.inspect(bind);tables=set(inspector.get_table_names())
    if "provider_credentials" not in tables:op.create_table("provider_credentials",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("provider",sa.String(80),nullable=False),sa.Column("encrypted_credential",sa.Text(),nullable=False),sa.Column("key_version",sa.Integer(),nullable=False),sa.Column("masked_identifier",sa.String(32)),sa.Column("validation_status",sa.String(40),nullable=False),sa.Column("last_validated_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("user_id","provider",name="uq_provider_credential_owner"));op.create_index("ix_provider_credentials_user_id","provider_credentials",["user_id"])
    if "provider_models" not in tables:op.create_table("provider_models",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("provider",sa.String(80),nullable=False),sa.Column("model_id",sa.String(160),nullable=False),sa.Column("owned_by",sa.String(120)),sa.Column("provider_created_at",sa.DateTime(timezone=True)),sa.Column("context_window",sa.Integer()),sa.Column("modalities",sa.JSON()),sa.Column("capabilities",sa.JSON()),sa.Column("last_seen_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("user_id","provider","model_id",name="uq_provider_model_owner"));op.create_index("ix_provider_models_user_id","provider_models",["user_id"])
    if "pricing_records" not in tables:op.create_table("pricing_records",sa.Column("id",sa.String(36),primary_key=True),sa.Column("provider",sa.String(80),nullable=False),sa.Column("model",sa.String(160),nullable=False),sa.Column("effective_from",sa.DateTime(timezone=True),nullable=False),sa.Column("effective_to",sa.DateTime(timezone=True)),sa.Column("pricing_unit",sa.String(40),nullable=False),sa.Column("input_price",sa.Numeric(24,12),nullable=False),sa.Column("output_price",sa.Numeric(24,12),nullable=False),sa.Column("cached_input_price",sa.Numeric(24,12)),sa.Column("currency",sa.String(3),nullable=False),sa.Column("region",sa.String(80)),sa.Column("provenance",sa.String(500),nullable=False),sa.Column("last_verified_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("provider","model","effective_from","region",name="uq_pricing_version"));op.create_index("ix_pricing_records_provider","pricing_records",["provider"]);op.create_index("ix_pricing_records_model","pricing_records",["model"]);op.create_index("ix_pricing_records_effective_from","pricing_records",["effective_from"]);op.create_index("ix_pricing_records_effective_to","pricing_records",["effective_to"])
    columns={x["name"] for x in inspector.get_columns("telemetry_events")}
    with op.batch_alter_table("telemetry_events") as batch:
        if "provider_recorded_cost" not in columns:batch.add_column(sa.Column("provider_recorded_cost",sa.Numeric(24,12)))
        if "calculated_cost" not in columns:batch.add_column(sa.Column("calculated_cost",sa.Numeric(24,12)))
        if "pricing_record_id" not in columns:batch.add_column(sa.Column("pricing_record_id",sa.String(36)))
        if "provenance" not in columns:batch.add_column(sa.Column("provenance",sa.String(30),server_default="LEGACY",nullable=False))
    inspector=sa.inspect(bind);indexes={x["name"] for x in inspector.get_indexes("telemetry_events")}
    if "ix_telemetry_events_pricing_record_id" not in indexes:op.create_index("ix_telemetry_events_pricing_record_id","telemetry_events",["pricing_record_id"])
    if "ix_telemetry_events_provenance" not in indexes:op.create_index("ix_telemetry_events_provenance","telemetry_events",["provenance"])
    verified=datetime(2026,9,6,tzinfo=timezone.utc);effective=datetime(2026,9,6,tzinfo=timezone.utc)
    pricing=sa.table("pricing_records",sa.column("id",sa.String),sa.column("provider",sa.String),sa.column("model",sa.String),sa.column("effective_from",sa.DateTime(timezone=True)),sa.column("effective_to",sa.DateTime(timezone=True)),sa.column("pricing_unit",sa.String),sa.column("input_price",sa.Numeric),sa.column("output_price",sa.Numeric),sa.column("cached_input_price",sa.Numeric),sa.column("currency",sa.String),sa.column("region",sa.String),sa.column("provenance",sa.String),sa.column("last_verified_at",sa.DateTime(timezone=True)))
    existing=bind.execute(sa.select(sa.func.count()).select_from(pricing)).scalar() or 0
    if not existing:
        rows=[("price-openai-gpt-6-astra-20260906","gpt-6-astra",10,50,1),("price-openai-gpt-5-6-sol-20260906","gpt-5.6-sol",4,20,.4),("price-openai-gpt-5-6-terra-20260906","gpt-5.6-terra",2,12,.2),("price-openai-gpt-5-6-luna-20260906","gpt-5.6-luna",.2,1.2,.02)]
        op.bulk_insert(pricing,[{"id":id_,"provider":"openai","model":model,"effective_from":effective,"effective_to":None,"pricing_unit":"PER_MILLION_TOKENS","input_price":str(inp),"output_price":str(out),"cached_input_price":str(cached),"currency":"USD","region":None,"provenance":SOURCE,"last_verified_at":verified} for id_,model,inp,out,cached in rows])
def downgrade():
    with op.batch_alter_table("telemetry_events") as batch:batch.drop_index("ix_telemetry_events_provenance");batch.drop_index("ix_telemetry_events_pricing_record_id");batch.drop_column("provenance");batch.drop_column("pricing_record_id");batch.drop_column("calculated_cost");batch.drop_column("provider_recorded_cost")
    op.drop_table("pricing_records");op.drop_table("provider_models");op.drop_table("provider_credentials")
